cors:
  allowed-origin: https://wisewealth.firm.in
  extra-origins: https://www.wisewealth.firm.in

spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
