cors:
  allowed-origin: http://localhost:3000
  extra-origins: http://localhost:8080

spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
