cors:
  allowed-origin: http://localhost:3000
  extra-origins: http://localhost:8080

spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: b0e0d3001@smtp-brevo.com
    password: xsmtpsib-9027b7a464bbbfa70b8722180065ae45225cdbb26d758e24c266a4c4b87fc0bc-Z1gBitW2SPqwBhE4

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
